# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/cli/main.go
    ldflags: -s -w -X main.version="{{.Version}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    no_unique_dist_dir: true
    binary: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
archives:
  - format_overrides:
    - goos: windows
      format: zip
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
