language: go

go:
  - "1.12.x"

notifications:
  email: false

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run
  - go test -v ./... -race -cover -coverprofile=coverage.txt -covermode=atomic

after_success:
- export CODECOV_TOKEN="ec1a7246-d903-4451-a62f-555edccf3d4c"
- bash <(curl -s https://codecov.io/bash)
