language: go

go:
  - "1.17.x"

notifications:
  email: false

env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

script:
  - golangci-lint run
  - go test -v ./... -race -cover -coverprofile=coverage.txt -covermode=atomic

after_success:
- export CODECOV_TOKEN="9368e0b4-bb9f-4786-a938-343a33c89672"
- bash <(curl -s https://codecov.io/bash)
